export const GET_TODOS = 'GET_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'
